DROP INDEX IF EXISTS instrument_services.idx_watched_instruments_active;
DROP INDEX IF EXISTS instrument_services.idx_watched_instruments_interval;
DROP INDEX IF EXISTS instrument_services.idx_watched_instruments_uid;
DROP INDEX IF EXISTS instrument_services.idx_watched_instruments_figi;