-- Create ENUM types
CREATE TYPE instrument_services.share_type AS ENUM (
    'SHARE_TYPE_UNSPECIFIED',
    'SHARE_TYPE_COMMON',
    'SHARE_TYPE_PREFERRED',
    'SHARE_TYPE_ADR',
    'SHARE_TYPE_GDR',
    'SHARE_TYPE_MLP',
    'SHARE_TYPE_NY_REG_SHRS',
    'SHARE_TYPE_CLOSED_END_FUND',
    'SHARE_TYPE_REIT'
);

CREATE TYPE instrument_services.security_trading_status AS ENUM (
    'SECURITY_TRADING_STATUS_UNSPECIFIED',
    'SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING',
    'SECURITY_TRADING_STATUS_OPENING_PERIOD',
    'SECURITY_TRADING_STATUS_CLOSING_PERIOD',
    'SECURITY_TRADING_STATUS_BREAK_IN_TRADING',
    'SECURITY_TRADING_STATUS_NORMAL_TRADING',
    'SECURITY_TRADING_STATUS_CLOSING_AUCTION',
    'SECURITY_TRADING_STATUS_DARK_POOL_AUCTION',
    'SECURITY_TRADING_STATUS_DISCRETE_AUCTION',
    'SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD',
    'SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE',
    'SECURITY_TRADING_STATUS_SESSION_ASSIGNED',
    'SECURITY_TRADING_STATUS_SESSION_CLOSE',
    'SECURITY_TRADING_STATUS_SESSION_OPEN',
    'SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING',
    'SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING',
    'SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING'
);

CREATE TYPE instrument_services.real_exchange AS ENUM (
    'REAL_EXCHANGE_UNSPECIFIED',
    'REAL_EXCHANGE_MOEX',
    'REAL_EXCHANGE_RTS',
    'REAL_EXCHANGE_OTC'
);

-- Create composite types
CREATE TYPE instrument_services.quotation AS (
    units BIGINT,
    nano INTEGER
);

CREATE TYPE instrument_services.money_value AS (
    currency VARCHAR(10),
    units BIGINT,
    nano INTEGER
);