[log]
level = "info,sqlx=info"
format = "text"            # Возможные значения: "json" или "text"

[postgres_db]
max_connections = 5
timeout_seconds = 10
pool_size = 2

[mongo_db]
timeout_seconds = 10
pool_size = 10             # MongoDB connections pool size
retry_writes = true       
write_concern = "majority" # Options: "majority", "1" (default), "2", etc.
read_concern = "local"     # Options: "local", "majority", "available", "linearizable"

[tinkoff_api]
base_url = "https://invest-public-api.tinkoff.ru:443"
domain = "invest-public-api.tinkoff.ru"
timeout = 30   # seconds
keepalive = 60 # seconds


[tinkoff_market_data_updater]
enabled = true
interval_seconds = 600  # 10 minute
max_retries = 3
retry_delay_seconds = 5
update_start_time = "07:00"
update_end_time = "23:59"
timezone = "Europe/Moscow"

[candles_tracking_updater]
enabled = true
interval_seconds = 605 
max_retries = 3
retry_delay_seconds = 5
update_start_time = "07:00"
update_end_time = "23:59"
timezone = "Europe/Moscow"

[stream_updater]
enabled = true
retry_attempts = 3
retry_delay_seconds = 5
trading_start_time = "07:00"
trading_end_time = "23:59"
timezone = "Europe/Moscow"