[log]
level = "debug,sqlx=debug"
format = "text"            # Возможные значения: "json" или "text"

[database]
max_connections = 5
timeout_seconds = 10
pool_size = 2

[tinkoff_api]
base_url = "https://invest-public-api.tinkoff.ru:443"
domain = "invest-public-api.tinkoff.ru"
timeout = 30   # seconds
keepalive = 60 # seconds


[share_updater]
enabled = false
interval_seconds = 60  # 1 minute for local development
max_retries = 3
retry_delay_seconds = 5
night_updates_disabled = true
night_start_time = "23:59"
night_end_time = "07:00"
timezone = "Europe/Moscow"