app_env = "local"
[log]
level = "debug,sqlx=debug"
format = "text"            # Возможные значения: "json" или "text"


[server]
address = "127.0.0.1"
port = 5000


[database]
url = ""
max_connections = 5
timeout_seconds = 10
# Get database connection pool size
pool_size = 2

[grpc_tinkoff]
base_url = "https://invest-public-api.tinkoff.ru:443"
domain = "invest-public-api.tinkoff.ru"
token = ""

[grpc_cient]
timeout = 30   # seconds
keepalive = 60 # seconds
