[log]
level = "debug,sqlx=debug"
format = "text"            # Возможные значения: "json" или "text"

[server]
address = "0.0.0.0"
port = 5000


[database]
max_connections = 5
timeout_seconds = 10
pool_size = 2

[tinkoff_api]
base_url = "https://invest-public-api.tinkoff.ru:443"
domain = "invest-public-api.tinkoff.ru"

[client_rest]
timeout = 30   # seconds
keepalive = 60 # seconds


[tinkoff_instruments_updater]
enabled = true
interval_seconds = 300  # 5 minutes for production
max_retries = 5
retry_delay_seconds = 10