CREATE TYPE instrument_services.candle_interval AS ENUM (
    'CANDLE_INTERVAL_UNSPECIFIED',
    'CANDLE_INTERVAL_1_MIN',
    'CANDLE_INTERVAL_5_MIN',
    'CANDLE_INTERVAL_15_MIN',
    'CANDLE_INTERVAL_HOUR',
    'CANDLE_INTERVAL_DAY'
);